POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxhc3NpIiwiaWQiOiI2MzQ4MzgxZjI1MzBjYThmNWU4NGQ2ZDAiLCJpYXQiOjE2NjU2NzgwMDB9.Z50WYXBSuk2K2-CAOFs4jQ2ADXj6aCgKb6kBz0-2G_Y

{
    "content": "Posting a new note using tokens to authenticate!",
    "important": true
}